apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-depl-as
  labels:
    app: my-k8s-app
    env: prod
    owner: iam
spec:
  replicas: 2
  selector:
    matchLabels:
      project: sad
  template:
    metadata:
      labels:
        project: sad
    spec:
      containers:
        - name: sad-web
          image: asafsaf/k8s-test:latest
          ports:
            - containerPort: 8089
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-as
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-depl-as
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
