apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dep
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      project: hello-app
  template:
    metadata:
      labels:
        project: hello-app
    spec:
      containers:
        - name: hello-web
          image: asafsaf/k8s-test:latest
          ports:
            - containerPort: 8089

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bye-dep
  labels:
    app: bye-app
spec:
  replicas: 2
  selector:
    matchLabels:
      project: bye-app
  template:
    metadata:
      labels:
        project: bye-app
    spec:
      containers:
        - name: bye-web
          image: asafsaf/demo:latest
          ports:
            - containerPort: 8090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-dep
  labels:
    app: sleep-app
spec:
  replicas: 2
  selector:
    matchLabels:
      project: sleep-app
  template:
    metadata:
      labels:
        project: sleep-app
    spec:
      containers:
        - name: sleep-web
          image: asafsaf/sleep:latest
          ports:
            - containerPort: 8091
