apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    env: prod
    app: main
    tier: frontend
    owner: Aliaskandr
spec:
  containers:
    - name: container-app
      image: asafsaf/k8s-test:latest
      ports:
        - containerPort: 8089