apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    env: prod
    app: main
    tier: frontend
    owner: Aliaskandr
spec:
  containers:
    - name: container-web
      image: nginx:latest
      ports:
        - containerPort: 8088
    - name: container-api
      image: asafsaf/k8s-test:latest
      ports:
        - containerPort: 8089