apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-depl-repl
  labels:
    app: my-k8s-app
    env: prod
    owner: iam
spec:
  selector:
    matchLabels:
      project: fbi
  template:
    metadata:
      labels:
        project: fbi  # Selector will look for those Pods label.
    spec:
      containers:
        - name: fbi-web
          image: asafsaf/k8s-test:latest
          ports:
            - containerPort: 8089

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-as
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-depl-repl
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    env: prod
    owner: iam
spec:
  type: LoadBalancer
  selector:
    project: fbi    # Selecting Pods by labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 8089    # Port on LoadBalancer
      targetPort: 8089  # Port on Pod