apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-depl-repl
  labels:
    app: my-k8s-app
    env: prod
    owner: iam
spec:
  replicas: 3
  selector:
    matchLabels:
      project: fbi
  template:
    metadata:
      labels:
        project: fbi  # Selector will look for those Pods label.
    spec:
      containers:
        - name: fbi-web
          image: asafsaf/k8s-test:latest
          ports:
            - containerPort: 8089
        - name: my-web
          image: asafsaf/demo:latest
          ports:
            - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    env: prod
    owner: iam
spec:
  type: LoadBalancer
  selector:
    project: fbi    # Selecting Pods by labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 8089    # Port on LoadBalancer
      targetPort: 8089  # Port on Pod
    - name: my-web-app-listener
      protocol: TCP
      port: 8090    # Port on LoadBalancer
      targetPort: 8090  # Port on Pod